### ISSUE TITLE
サークルカットを作る

### ISSUE THREAD

**Issue by cattaka** [wantedly/tech-book#13]
## WHY
サークル申込のため。

## WHAT
サークルカットを作る

## やることリスト
- [ ] サークルカットを作る( @yanAoym  )
- [ ] サークル情報に登録する( @cattaka )

**Comment by cattaka** [comment]
## サイズ
- サークルカットのテンプレートデータはコミックマーケットフォーマット（タイプA）に準拠します
 - 画像縦:903px、横:635px
 - フォーマット:PNG

https://techbookfest.github.io/circle.html より

**Comment by yanAoym** [comment]
@cattaka 締め日は何時ですかー？

**Comment by cattaka** [comment]
期日：〜4/25 24:00

**Comment by cattaka** [comment]
@yanAoym 行けそうですか？

**Comment by yanAoym** [comment]
![circle-01](https://cloud.githubusercontent.com/assets/12505291/14788954/42889616-0b45-11e6-9fbf-cffa9ed80079.png)

**Comment by cattaka** [comment]
ありがとうございます！
