### ISSUE TITLE
申し込み周り

### ISSUE THREAD

**Issue by cattaka** [wantedly/tech-book#14]
## WHAT
申し込み周りの作業

**Comment by cattaka** [comment]
## やることリスト
- [x] 申し込む
- [x] 申し込みの合否の確認
- [x] 参加費の振込

**Comment by cattaka** [comment]
技術書典 事務局(mhidaka) から 自分
もっと見る
4月30日
技術書典 事務局です。

この度は技術書典へのサークル参加申し込み、誠にありがとうございました。

◎貴サークル「Wantedly執筆部」は、キ-08 に配置されました。

  ※※※参加費の入金をもって確定となります（期日にご注意下さい）※※※

配置図
 https://storage.googleapis.com/techbookfest-static/techbookfest-space/layout.png

想定を超える多数の応募をいただき、フロアを追加いたしました。
当日は通運会館の2階と地下1階で開催いたします。
また残念ながら落選してしまったサークル向けのサービスとして
委託ブース（B1F運営本部合同）を用意しています。

以下に技術書典のサークル向け詳細情報を記載しています。
参加費の振り込み、搬入情報、当日スケジュールの概要、製本バックアップ情報などです。

□………………………………………………………………………………………………
■　参加費のお振り込み先
□………………………………………………………………………………………………
技術書典の参加費は個人:5000円、企業:10000円です。
振込名義は、サークル代表者またはサークル名でお願いします。

5/10(火)までに以下（代表者の口座です）にお振り込みください。
振込確認をもって参加確定となります。

※企業の場合時期は、ご相談可能ですのでお振り込み見通しをご連絡ください。

金融機関名：三井住友銀行 支店：大阪本店営業部(支店コード101)
普通口座：6852819
口座名義：日高 正博
口座名義（カナ）：ヒダカ マサヒロ

□………………………………………………………………………………………………
■　会場についてご案内
□………………………………………………………………………………………………
イベント当日6/25（土）のスケジュールは次のとおりです。

出展入場：10時～
来場入場：11時～
終了時刻：17時
出展者撤収：17時～18時

サークル入場チケット（入場確認できるメール）は5/10以降、詳細をメールにて送付いたします

□………………………………………………………………………………………………
■　搬入情報
□………………………………………………………………………………………………
宅配は以下の宛先にお送りください。

※時間帯指定として"6月24日/午前"を必ずご指定ください。
※備考欄に"「サークル名／配置番号」または「委託」"をご記入ください。

宛先：通運会館 技術書典事務局
住所：101-0021 東京都千代田区外神田3-16-18
電話：03（3253）5291
時間帯指定 6/24（金） 午前着

当日搬入の場合、車の横付けが可能です。
駐車スペースはございませんので、予め近隣の駐車場を確保ください。
※長時間の作業になる場合は、ご相談ください

バックアップ印刷所である日光企画さまご利用の場合、直接搬入です。
その他印刷所の場合は、印刷所様まで搬入条件をご確認ください。

□………………………………………………………………………………………………
■　技術書典について
□………………………………………………………………………………………………
技術書典を運営しているTechBooster/達人出版会では、技術書の普及のため
勉強会の開催など同人誌づくりが初めての方に向けたバックアップを行っています。

http://techbookfest.connpass.com/

イベント参加にあたっての立場は運営者、出展者、一般来場者とさまざまですが
技術書典では、参加者が技術を知り、楽しめる場にしたい、と考えています。

多くのサークル出展者さまは経験が豊かで、自分なりの印刷、製本技術を持っており、
活動されている一方で、同人誌を初めて作る方にとっては、本作りそのものが難しい現状もあります。
技術書典では、初めての方を積極的にサポートすることで個々人が積み重ねてきた技術や成果、
ノウハウを共有し、技術の普及を推進していきたいと考えています。

□………………………………………………………………………………………………
■　印刷バックアップ情報
□………………………………………………………………………………………………
技術書典では、勉強会の開催など同人誌づくりが初めての方に向けた印刷の支援、
バックアップを企画しています。利用は必須ではございません。

支援の一環として入稿用データのビルドサービス、
オンデマンド印刷を活用した印刷サービスを提供予定です。

どちらも初めての試みであり調整中ですので、最終的にどこまで実現できるか
現状でお約束できない点は心苦しいですが、詳細が決まり次第またメールにて連絡いたします。

・入稿用PDFのビルド環境提供（全サークル向け）
　- 成果物の確認と印刷所とのやりとりを自動化するサービスです
　- GitHubとRe:VIEWをつかって原稿を書いている場合に利用できます
 - コミットごと入稿用PDFを生成するサーバーです
 - IPAフォントを埋め込みます。判型はB5正寸です
 - イベント特製表紙を提供します（表紙をご用意いただくことも可能です）
 - バックアップ印刷所である日光企画さまと後述のオンデマンド印刷で利用できます

・当日の追加注文システム（出展サークル向け）
  - 原稿PDFを事前にお預け頂く必要があります
  - 12時や14時など区切りで注文を受け付け、1時間程度で納品します
  - 購入者の希望があれば後日の直接郵送も可能です
  - 負担となる印刷価格に折り合いがつかなければ中止するかもしれません

==========================================================================
※ このメールアドレスはZenDeskを利用して送信しています。
　 ご質問などはこのメールに直接返信いただけると担当者より回答いたします。

　 技術書典 事務局
==========================================================================

**Comment by mhidaka** [comment]
技術書典代表です。
銀行口座および出展者向け情報、受付指定など各種出展者向け情報は広く開示していません。記載を削除いただけますか

**Comment by mhidaka** [comment]
@cattaka よろしくご対応ください

**Comment by cattaka** [comment]
@mhidaka すみません。削除しました。
